name = "globlin"
version = "2.0.2"
description = "file globbing for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "apainintheneck", repo = "globlin" }
links = [{ title = "Globlin File System Package", href = "https://hexdocs.pm/globlin_fs/index.html" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
