name = "globlin"
version = "1.0.1"
description = "file globbing for Gleam"
licences = ["MIT"]
repository = { type = "github", user = "apainintheneck", repo = "globlin" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
simplifile = ">= 2.0.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
